version: '3.4'
services:
  frontend:
    build:
      context: apps/frontend
    ports:
      - "8080:8080"
  api:
    build:
      context: apps/api
    ports:
      - "8081:8080"
  database:
    image: postgres:15-alpine
    ports:
      - "8082:5432"
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dora-metrics