DROP TABLE IF EXISTS event cascade ;
DROP TABLE IF EXISTS deployment cascade;
DROP TABLE IF EXISTS migration cascade;

DROP DOMAIN IF EXISTS ksuid RESTRICT;
DROP DOMAIN IF EXISTS url RESTRICT;
DROP DOMAIN IF EXISTS environment RESTRICT;
DROP DOMAIN IF EXISTS status RESTRICT;
DROP DOMAIN IF EXISTS event_type RESTRICT;